spring:
  application:
    name: task-tracker-mailer
    version: 1.0.0

  config:
    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: mailer
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: ru.giv13.common.event
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      user:
        registered: ${KAFKA_USER_REGISTERED_TOPIC_NAME}
        logged-in: ${KAFKA_USER_LOGGED_IN_TOPIC_NAME}
        task-summary: ${KAFKA_USER_TASK_SUMMARY_TOPIC_NAME}

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    sender:
      email: ${SMTP_SENDER_EMAIL:${SMTP_USERNAME}}
      name: ${SMTP_SENDER_NAME:Task tracker}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082
