spring:
  application:
    name: task-tracker-scheduler
    version: 1.0.0

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 20000
        request.timeout.ms: 5000
    topics:
      user:
        task-summary: ${KAFKA_USER_TASK_SUMMARY_TOPIC_NAME}

logging:
  level:
    org.springframework:
      jdbc.core: DEBUG

server:
  port: 8081
