spring:
  application:
    name: task-tracker-backend
    version: 1.0.0

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 20000
        request.timeout.ms: 5000
    topics:
      user:
        registered: ${KAFKA_USER_REGISTERED_TOPIC_NAME}
        password-changed: ${KAFKA_USER_PASSWORD_CHANGED_TOPIC_NAME}

  liquibase:
    change-log: db/changelog/changelog-root.yaml
    enabled: true

  messages:
    basename: properties.validation

encryptor:
  password: ${ENCRYPTOR_PASSWORD}
  salt: ${ENCRYPTOR_SALT}

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 15m
    token-name: token
    refresh:
      expiration: 30d
      token-name: refresh