name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.check.outputs.frontend_changed }}
      backend-changed: ${{ steps.check.outputs.backend_changed }}
      scheduler-changed: ${{ steps.check.outputs.scheduler_changed }}
      mailer-changed: ${{ steps.check.outputs.mailer_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        id: check
        run: |
          if git merge-base ${{ github.event.before }} ${{ github.sha }} >/dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          else
            CHANGED_FILES=$(git show --name-only --pretty=format: ${{ github.sha }})
          fi
          for folder in frontend backend scheduler mailer; do
            if echo "$CHANGED_FILES" | grep -q "^$folder/"; then
              echo "${folder}_changed=true" >> $GITHUB_OUTPUT
            else
              echo "${folder}_changed=false" >> $GITHUB_OUTPUT
            fi
          done

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push task-tracker-frontend
        if: needs.check-changes.outputs.frontend-changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-tracker-frontend:latest

      - name: Build and push task-tracker-backend
        if: needs.check-changes.outputs.backend-changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-tracker-backend:latest

      - name: Build and push task-tracker-scheduler
        if: needs.check-changes.outputs.scheduler-changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./scheduler/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-tracker-scheduler:latest

      - name: Build and push task-tracker-mailer
        if: needs.check-changes.outputs.mailer-changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mailer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-tracker-mailer:latest